using System;
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.SceneManagement;

public enum GameState { FreeRoam, Battle, Dialog, Menu, Cutscene, Paused,Bag }
public class GameManager : MonoBehaviour
{
    [SerializeField] private PlayerController playerController;
    [SerializeField] private BattleSystem battleSystem;
    [SerializeField] private Camera worldCamera;
    [SerializeField] private InventoryUI inventoryUI;
    //[SerializeField] private AudioClip victoryMusic;
    //[SerializeField] private AudioClip gameOverMusic;

    private GameState state;
    private GameState prevState;

    //CAMBIO POR ADDITIVE SCENE
    private SceneDetails currentScene;
    private SceneDetails prevScene;

    private Menu menuController;
    public static GameManager Instance { get; private set; }
    
    //CAMBIO POR ADDITIVE SCENE
    public SceneDetails CurrentScene { get => currentScene; set => currentScene = value; }
    public SceneDetails PrevScene { get => prevScene; set => prevScene = value; }

    private int wildPokemonsDefeated;

    private void Awake()
    {
        Instance = this;

        menuController = GetComponent<Menu>();
    }

    private void Start()
    {
        wildPokemonsDefeated = 0;

        battleSystem.onBattleOver += EndBattle;

        //partyScreen.Init();

        DialogManager.Instance.OnShowDialog += () =>
        {
            prevState = state;
            state = GameState.Dialog;
        };

        DialogManager.Instance.OnDialogFinished += () =>
        {
            if (state == GameState.Dialog)
                state = prevState;
        };

        menuController.onBack += () =>
        {
            state = GameState.FreeRoam;
        };

        menuController.onMenuSelected += OnMenuSelected;
    }

    public void PauseGame(bool pause)
    {
        if (pause)
        {
            prevState = state;
            state = GameState.Paused;
        }
        else
        {
            state = prevState;
        }
    }

    public void StartBattle()
    {
        state = GameState.Battle;
        battleSystem.gameObject.SetActive(true);
        worldCamera.gameObject.SetActive(false);

        var playerParty = playerController.GetComponent<PokemonParty>();
        var wildPokemon = CurrentScene.GetComponent<MapArea>().GetRandomWildPokemon();

        //var wildPokemonCopy = new Pokemon(wildPokemon.Base, wildPokemon.Level);

        battleSystem.StartBattle(playerParty, wildPokemon);
    }

    /*
    TrainerController trainer;
    public void StartTrainerBattle(TrainerController trainer)
    {
        state = GameState.Battle;
        battleSystem.gameObject.SetActive(true);
        worldCamera.gameObject.SetActive(false);

        this.trainer = trainer;
        var playerParty = playerController.GetComponent<PokemonParty>();
        var trainerParty = trainer.GetComponent<PokemonParty>();

        battleSystem.StartTrainerBattle(playerParty, trainerParty);
    }

    public void OnEnterTrainersView(TrainerController trainer)
    {
        state = GameState.Cutscene;
        StartCoroutine(trainer.TriggerTrainerBattle(playerController));
    }
    */
    void EndBattle(bool won,bool isRunning)
    {
        state = GameState.FreeRoam;
        battleSystem.gameObject.SetActive(false);
        worldCamera.gameObject.SetActive(true);
        AudioManager.instance.PlayMusic(CurrentScene.SceneMusic, fade: true);

        if (isRunning) return;

        if (won) wildPokemonsDefeated++;

        if(wildPokemonsDefeated == 2 || !won)
            FinishGame(won);
    }

    private void Update()
    {
        if (state == GameState.FreeRoam)
        {
            playerController.HandleUpdate();

            if (Input.GetKeyDown(KeyCode.Return))
            {
                menuController.OpenMenu();
                state = GameState.Menu;
            }
        }
        else if (state == GameState.Battle)
        {
            battleSystem.HandleUpdate();
        }
        else if (state == GameState.Dialog)
        {
            DialogManager.Instance.HandleUpdate();
        }
        else if (state == GameState.Menu)
        {
            menuController.HandleUpdate();
        }
        /*
        else if (state == GameState.PartyScreen)
        {
            Action onSelected = () =>
            {
                // TODO: Go to Summary Screen
            };

            Action onBack = () =>
            {
                partyScreen.gameObject.SetActive(false);
                state = GameState.FreeRoam;
            };

            partyScreen.HandleUpdate(onSelected, onBack);
        }*/
        else if (state == GameState.Bag)
        {
            Action onBack = () =>
            {
                inventoryUI.gameObject.SetActive(false);
                state = GameState.FreeRoam;
            };

            inventoryUI.HandleUpdate(onBack);
        }
    }

    public void SetCurrentScene(SceneDetails currScene)
    {
        PrevScene = CurrentScene;
        CurrentScene = currScene;
    }

    void OnMenuSelected(int selectedItem)
    {
        if (selectedItem == 0)
        {
            // Pokemon
            //partyScreen.gameObject.SetActive(true);
            //state = GameState.PartyScreen;
        }
        else if (selectedItem == 1)
        {
            // Bag
            inventoryUI.gameObject.SetActive(true);
            state = GameState.Bag;
        }
        else if (selectedItem == 2)
        {
            // Save
            //SavingSystem.i.Save("saveSlot1");
            state = GameState.FreeRoam;
        }
        else if (selectedItem == 3)
        {
            // Load
            //SavingSystem.i.Load("saveSlot1");
            state = GameState.FreeRoam;
        }
    }

    private void FinishGame(bool conditionToWin)
    {
        DestroyLevelPackObject();

        if (conditionToWin)
        {
            SceneManager.LoadScene("Victory");
        }

        else
        {
            SceneManager.LoadScene("GameOver");
        }
    }

    private void DestroyLevelPackObject()
    {
        var existingObjects = FindObjectsOfType<EssentialObjects>();
        foreach (var obj in existingObjects)
        {
            Destroy(obj.gameObject);
        }
    }

    public GameState State => state;
}
